### PR TITLE
V2.1

### PR DESCRIPTION
**Pull request by marlonmarcello**
Lots of updated here. All learnings from using the bootstrap for the first time on a project.
They range from small bugs and fixes to full overhauls.
Important ones:

- Added a `LOCALE_ROOT` variable for internal links
- Fixed a problem with the build process where it wouldn't compile if a file needed to be prettified
- Updated the environment variables with a staging/pub option
- Improved javscripts, styles, prettier and templates bundling
- Fixed the bundling order
- Removed stylesheet prefetching, this was a request ☹️
- Updated README
- Added a full documentation on all of the bundled components ✨

### CODE REVIEW

**Comment by liamegan** [comment]
We have decided *not* to make nested media queries standard (for now). It produces too much crappy code on compile and any attempts to resolve that inevitably require external processing which we haven't tested.

**Comment by marlonmarcello** [comment]
@liamegan it was tested on fire emblem, it's up on production the files are processed and cleaned.

**Comment by marlonmarcello** [comment]
@NicholasLancey we do not, we can make one easy, send me suggestions.

**Comment by NicholasLancey** [comment]
@marlonmarcello I'll make a pull request

**Pull request merged**
